---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello02
  labels:
    app: hello02
spec:
  selector:
    matchLabels:
      app: hello02
  replicas: 1
  template:
    metadata:
      labels:
        app: hello02
    spec:
      restartPolicy: Always
      containers:
        - name: hello02
          image: ghcr.io/conoa/hello02:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
