---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello01
  labels:
    app: hello01
spec:
  selector:
    matchLabels:
      app: hello01
  replicas: 1
  template:
    metadata:
      labels:
        app: hello01
    spec:
      restartPolicy: Always
      containers:
        - name: hello01
          image: ghcr.io/conoa/hello01:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
