apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause
  labels:
    app: pause
  finalizers:
    - k8s.extension.conoa.se/v1beta1  
spec:
  selector:
    matchLabels:
      app: pause
  replicas: 1
  template:
    metadata:
      labels:
        app: pause
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pause
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.9
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 10m
              memory: 10Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
      restartPolicy: Always
